### ISSUE TITLE
Error: Version 2.0 of dune is not supported.

### ISSUE THREAD

**Issue by chengtie** [ocaml/ocaml-lsp#138]
I want to try ocaml-lsp, however, it gave me an `Error: Version 2.0 of dune is not supported.`

```
$ git clone --recurse-submodules http://github.com/ocaml/ocaml-lsp.git
... ...
$ cd ocaml-lsp
$ make build
dune build
File "dune-project", line 1, characters 11-14:
1 | (lang dune 2.0)
               ^^^
Error: Version 2.0 of dune is not supported.
Supported versions:
- 0.0
- 1.0 to 1.11
make: *** [build] Error 1
```

My `dune --version` is `1.11.4` and `opam --version` is `2.0.2`. Does anyone know how to fix this?

**Comment by imbsky** [comment]
As you can see in the error message, you need dune 2.0.0 or later.

**Comment by imbsky** [comment]
```
opam update
opam upgrade dune
```

**Comment by chengtie** [comment]
Thank you, it is better. Now, I got another error:

```
$ make build
dune build
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 614, characters 29-36:
Warning: the token COMMENT is unused.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 615, characters 30-39:
Warning: the token DOCSTRING is unused.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 617, characters 7-10:
Warning: the token EOL is unused.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 533, characters 7-22:
Warning: the token GREATERRBRACKET is unused.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 715, characters 0-15:
Warning: symbol parse_core_type is unreachable from any of the start symbol(s).
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 721, characters 0-13:
Warning: symbol parse_pattern is unreachable from any of the start symbol(s).
File "lsp/bin/ocaml/ml.ml", line 308, characters 17-22:
Error: Syntax error: operator expected.
File "lsp/bin/ocaml/ocaml.ml", line 859, characters 15-19:
Error: Syntax error: operator expected.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 668, characters 0-9:
Warning: the precedence level assigned to GREATERDOT is never useful.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 653, characters 0-9:
Warning: the precedence level assigned to LBRACKETATAT is never useful.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 668, characters 0-9:
Warning: the precedence level assigned to LBRACKETPERCENTPERCENT is never useful.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 662, characters 0-9:
Warning: the precedence level assigned to below_SHARP is never useful.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 1354, characters 22-33:
Warning: this %prec declaration is never useful.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 1381, characters 46-57:
Warning: this %prec declaration is never useful.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 1383, characters 31-42:
Warning: this %prec declaration is never useful.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 1470, characters 44-55:
Warning: this %prec declaration is never useful.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 1472, characters 42-53:
Warning: this %prec declaration is never useful.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 1646, characters 28-39:
Warning: this %prec declaration is never useful.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 1652, characters 31-42:
Warning: this %prec declaration is never useful.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 1640, characters 22-33:
Warning: this %prec declaration is never useful.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 965, characters 66-76:
Warning: this %prec declaration is never useful.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 2286, characters 28-39:
Warning: this %prec declaration is never useful.
File "vendor/merlin/src/ocaml/preprocess/parser_raw.mly", line 2288, characters 45-56:
Warning: this %prec declaration is never useful.
make: *** [build] Error 1
```

Is it normal?

**Comment by imbsky** [comment]
What version of the OCaml compiler do you use?

**Comment by chengtie** [comment]
`ocaml --version` returns `4.07.1`.

**Comment by rgrinberg** [comment]
This was the error:

```
File "lsp/bin/ocaml/ml.ml", line 308, characters 17-22:
Error: Syntax error: operator expected.
File "lsp/bin/ocaml/ocaml.ml", line 859, characters 15-19:
Error: Syntax error: operator expected.
```

It should be now fixed.

**Comment by imbsky** [comment]
Fixed by https://github.com/ocaml/ocaml-lsp/commit/d7a127a14cc956b48eb06b42c5e663ec66375b41.

**Comment by chengtie** [comment]
`make build` works, thank you.

But `make test` still returns error:

`(base) Ties-MacBook-Pro:ocaml-lsp chengtie$ make build
dune build
(base) Ties-MacBook-Pro:ocaml-lsp chengtie$ make test
dune build @install
cd ocaml-lsp-server/test/e2e && dune exec -- yarn test
Entering directory '/Users/chengtie/Startup/OCamlProjects/ocaml-lsp'
yarn run v1.21.1
$ jest --forceExit
 FAIL  __tests__/textDocument-formatting.test.ts
  ● textDocument/formatting › reformatter binary present › can format an ocaml impl file

    Unable to find ocamlformat binary

      at handleResponse (node_modules/vscode-jsonrpc/lib/main.js:436:48)
      at processMessageQueue (node_modules/vscode-jsonrpc/lib/main.js:263:17)
      at Immediate.<anonymous> (node_modules/vscode-jsonrpc/lib/main.js:247:13)

  ● textDocument/formatting › reformatter binary present › can format an ocaml intf file

    Unable to find ocamlformat binary

      at handleResponse (node_modules/vscode-jsonrpc/lib/main.js:436:48)
      at processMessageQueue (node_modules/vscode-jsonrpc/lib/main.js:263:17)
      at Immediate.<anonymous> (node_modules/vscode-jsonrpc/lib/main.js:247:13)

 PASS  __tests__/textDocument-rename.test.ts
 PASS  __tests__/textDocument-codeAction.test.ts
 PASS  __tests__/TextDocument.test.ts
 PASS  __tests__/textDocument-documentHighlight.test.ts
 PASS  __tests__/textDocument-foldingRange.test.ts
 PASS  __tests__/textDocument-typeDefinition.test.ts
 PASS  __tests__/textDocument-documentSymbol.ts
 PASS  __tests__/textDocument-references.test.ts
 PASS  __tests__/textDocument-hover.test.ts
 PASS  __tests__/textDocument-codeLens.test.ts
 PASS  __tests__/Lifecycle.test.ts
 PASS  __tests__/textDocument-definition.test.ts
 PASS  __tests__/Request.Debug.test.ts
 PASS  __tests__/textDocument-selectionRange.test.ts

Test Suites: 1 failed, 1 skipped, 14 passed, 15 of 16 total
Tests:       2 failed, 11 skipped, 30 passed, 43 total
Snapshots:   0 total
Time:        3.697s
Ran all test suites.
Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [test] Error 1
```

Do you have any idea?

**Comment by imbsky** [comment]
Is ocamlformat installed?

**Comment by chengtie** [comment]
After `opam install ocamlformat`, `make test` works. Thank you.

**Comment by imbsky** [comment]
You're welcome. We handle error messages very carefully, so basically all error messages have answers 🙂
