### ISSUE TITLE
spawn Unknown system error -8

### ISSUE THREAD

**Issue by cnmade** [ocaml/ocaml-lsp#731]
I am using MacOS 12, with Intel cpu,
I am using VSCode with Ocaml extension
```
workbench.desktop.main.js:2693 Error: spawn Unknown system error -8
	at ChildProcess.spawn (node:internal/child_process:412:11)
	at Object.spawn (node:child_process:718:9)
	at /Users/nomore/.vscode/extensions/ocamllabs.ocaml-platform-1.10.4/dist/vscode_ocaml_platform.bc.js:1590:3510782
	at caml_call2 (/Users/nomore/.vscode/extensions/ocamllabs.ocaml-platform-1.10.4/dist/vscode_ocaml_platform.bc.js:41:507)
	at f_safe (/Users/nomore/.vscode/extensions/ocamllabs.ocaml-platform-1.10.4/dist/vscode_ocaml_platform.bc.js:1590:379656)
	at caml_call_gen (/Users/nomore/.vscode/extensions/ocamllabs.ocaml-platform-1.10.4/dist/vscode_ocaml_platform.bc.js:39:58227)
	at /Users/nomore/.vscode/extensions/ocamllabs.ocaml-platform-1.10.4/dist/vscode_ocaml_platform.bc.js:39:94961
	at new Promise (<anonymous>)
	at make$1 (/Users/nomore/.vscode/extensions/ocamllabs.ocaml-platform-1.10.4/dist/vscode_ocaml_platform.bc.js:1590:379698)
	at output$3 (/Users/nomore/.vscode/extensions/ocamllabs.ocaml-platform-1.10.4/dist/vscode_ocaml_platform.bc.js:1590:3510543)
	at _bDH_ (/Users/nomore/.vscode/extensions/ocamllabs.ocaml-platform-1.10.4/dist/vscode_ocaml_platform.bc.js:1590:3518591)
	at caml_call1 (/Users/nomore/.vscode/extensions/ocamllabs.ocaml-platform-1.10.4/dist/vscode_ocaml_platform.bc.js:41:427)
	at fulfilled_safe (/Users/nomore/.vscode/extensions/ocamllabs.ocaml-platform-1.10.4/dist/vscode_ocaml_platform.bc.js:1590:379887)
	at caml_call_gen (/Users/nomore/.vscode/extensions/ocamllabs.ocaml-platform-1.10.4/dist/vscode_ocaml_platform.bc.js:39:58227)
	at /Users/nomore/.vscode/extensions/ocamllabs.ocaml-platform-1.10.4/dist/vscode_ocaml_platform.bc.js:39:94961
```

**Comment by cnmade** [comment]
```
$ opam install ocaml-lsp-server
[NOTE] Package ocaml-lsp-server is already installed (current version is 1.9.0).
```

**Comment by cnmade** [comment]
```bash
$ dune --version
3.2.0
 $ ocamlc --version
4.12.0
```

**Comment by rgrinberg** [comment]
Try the latest version - 1.11.6. It will require upgrading OCaml to 4.14 unfortunately.

**Comment by cnmade** [comment]
Hello , @rgrinberg I upgrade to 1.11.6 and using ocaml 4.14, still got this problem 
```
 $ ocamllsp --version
1.11.6
$ ocamlc --version
4.14.0
```

**Comment by cnmade** [comment]
may be it a problem of vscode extension.
https://github.com/ocamllabs/vscode-ocaml-platform/issues/971

**Comment by cnmade** [comment]
I fixed it my self.
I have an very old opam, ocamlc.

I removed them , and reinstall latest ocaml, problem resolved.
